---
coffeescript:
  src: "/coffeescripts"
  target: "/public/javascripts"

haml:
  src: "/templates"
  target-file: "/public/templates.js"

scss:
  src: "/stylesheets"
  target: "/public/stylesheets"
